// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abfameweuwxtbckkoufc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZmFtZXdldXd4dGJja2tvdWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTI3NDEsImV4cCI6MjA2OTk2ODc0MX0.vViehXjApNeY6eB1pLVKzmd7cb6B6mk4UYjEzBZSJKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});